-- Convertir les montants Float → Int (centimes)
ALTER TABLE "Seller" ALTER COLUMN "totalSales" SET DATA TYPE INTEGER USING ROUND("totalSales")::INTEGER;
ALTER TABLE "Seller" ALTER COLUMN "totalEarnings" SET DATA TYPE INTEGER USING ROUND("totalEarnings")::INTEGER;
ALTER TABLE "Customer" ALTER COLUMN "totalSpent" SET DATA TYPE INTEGER USING ROUND("totalSpent")::INTEGER;
ALTER TABLE "Order" ALTER COLUMN "totalAmount" SET DATA TYPE INTEGER USING ROUND("totalAmount")::INTEGER;
ALTER TABLE "Order" ALTER COLUMN "taxAmount" SET DATA TYPE INTEGER USING ROUND("taxAmount")::INTEGER;
ALTER TABLE "Order" ALTER COLUMN "shippingCost" SET DATA TYPE INTEGER USING ROUND("shippingCost")::INTEGER;
ALTER TABLE "Order" ALTER COLUMN "discountAmount" SET DATA TYPE INTEGER USING ROUND("discountAmount")::INTEGER;
ALTER TABLE "OrderItem" ALTER COLUMN "unitPrice" SET DATA TYPE INTEGER USING ROUND("unitPrice")::INTEGER;
ALTER TABLE "OrderItem" ALTER COLUMN "totalPrice" SET DATA TYPE INTEGER USING ROUND("totalPrice")::INTEGER;
ALTER TABLE "OrderItem" ALTER COLUMN "commissionAmount" SET DATA TYPE INTEGER USING ROUND("commissionAmount")::INTEGER;
ALTER TABLE "OrderItem" ALTER COLUMN "sellerEarnings" SET DATA TYPE INTEGER USING ROUND("sellerEarnings")::INTEGER;
ALTER TABLE "Payment" ALTER COLUMN "amount" SET DATA TYPE INTEGER USING ROUND("amount")::INTEGER;
ALTER TABLE "Promotion" ALTER COLUMN "value" SET DATA TYPE INTEGER USING ROUND("value")::INTEGER;
ALTER TABLE "Promotion" ALTER COLUMN "minAmount" SET DATA TYPE INTEGER USING ROUND("minAmount")::INTEGER;
ALTER TABLE "SellerPayout" ALTER COLUMN "amount" SET DATA TYPE INTEGER USING ROUND("amount")::INTEGER;
